import React from 'react'
import Ciudades from '../Components/Ciudades';
import {CiudadesContext} from '../Contexts/CiudadesContextData'
import "../Css/Inicio.css";
export default function Inicio() {
  // const data={
  //   "location": {
  //   "name": "London",
  //   "region": "City of London, Greater London",
  //   "country": "United Kingdom",
  //   "lat": 51.52,
  //   "lon": -0.11,
  //   "tz_id": "Europe/London",
  //   "localtime_epoch": 1653600439,
  //   "localtime": "2022-05-26 22:27"
  //   },
  //   "current": {
  //   "last_updated_epoch": 1653599700,
  //   "last_updated": "2022-05-26 22:15",
  //   "temp_c": 16,
  //   "temp_f": 60.8,
  //   "is_day": 0,
  //   "condition": {
  //   "text": "Overcast",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
  //   "code": 1009
  //   },
  //   "wind_mph": 16.1,
  //   "wind_kph": 25.9,
  //   "wind_degree": 270,
  //   "wind_dir": "W",
  //   "pressure_mb": 1022,
  //   "pressure_in": 30.18,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 72,
  //   "cloud": 75,
  //   "feelslike_c": 16,
  //   "feelslike_f": 60.8,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "uv": 3,
  //   "gust_mph": 14.5,
  //   "gust_kph": 23.4
  //   },
  //   "forecast": {
  //   "forecastday": [
  //   {
  //   "date": "2022-05-26",
  //   "date_epoch": 1653523200,
  //   "day": {
  //   "maxtemp_c": 20,
  //   "maxtemp_f": 68,
  //   "mintemp_c": 10.4,
  //   "mintemp_f": 50.7,
  //   "avgtemp_c": 15.4,
  //   "avgtemp_f": 59.8,
  //   "maxwind_mph": 13.9,
  //   "maxwind_kph": 22.3,
  //   "totalprecip_mm": 0,
  //   "totalprecip_in": 0,
  //   "avgvis_km": 10,
  //   "avgvis_miles": 6,
  //   "avghumidity": 76,
  //   "daily_will_it_rain": 0,
  //   "daily_chance_of_rain": 0,
  //   "daily_will_it_snow": 0,
  //   "daily_chance_of_snow": 0,
  //   "condition": {
  //   "text": "Overcast",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
  //   "code": 1009
  //   },
  //   "uv": 3
  //   },
  //   "astro": {
  //   "sunrise": "04:55 AM",
  //   "sunset": "09:01 PM",
  //   "moonrise": "03:33 AM",
  //   "moonset": "04:41 PM",
  //   "moon_phase": "Waning Crescent",
  //   "moon_illumination": "21"
  //   },
  //   "hour": [
  //   {
  //   "time_epoch": 1653519600,
  //   "time": "2022-05-26 00:00",
  //   "temp_c": 11.8,
  //   "temp_f": 53.2,
  //   "is_day": 0,
  //   "condition": {
  //   "text": "Partly cloudy",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
  //   "code": 1003
  //   },
  //   "wind_mph": 8.3,
  //   "wind_kph": 13.3,
  //   "wind_degree": 255,
  //   "wind_dir": "WSW",
  //   "pressure_mb": 1018,
  //   "pressure_in": 30.07,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 89,
  //   "cloud": 30,
  //   "feelslike_c": 10.3,
  //   "feelslike_f": 50.5,
  //   "windchill_c": 10.3,
  //   "windchill_f": 50.5,
  //   "heatindex_c": 11.8,
  //   "heatindex_f": 53.2,
  //   "dewpoint_c": 10.1,
  //   "dewpoint_f": 50.2,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 12.8,
  //   "gust_kph": 20.5,
  //   "uv": 1
  //   },
  //   {
  //   "time_epoch": 1653523200,
  //   "time": "2022-05-26 01:00",
  //   "temp_c": 11.3,
  //   "temp_f": 52.3,
  //   "is_day": 0,
  //   "condition": {
  //   "text": "Partly cloudy",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
  //   "code": 1003
  //   },
  //   "wind_mph": 7.8,
  //   "wind_kph": 12.6,
  //   "wind_degree": 254,
  //   "wind_dir": "WSW",
  //   "pressure_mb": 1019,
  //   "pressure_in": 30.08,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 90,
  //   "cloud": 31,
  //   "feelslike_c": 9.8,
  //   "feelslike_f": 49.6,
  //   "windchill_c": 9.8,
  //   "windchill_f": 49.6,
  //   "heatindex_c": 11.3,
  //   "heatindex_f": 52.3,
  //   "dewpoint_c": 9.8,
  //   "dewpoint_f": 49.6,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 12.3,
  //   "gust_kph": 19.8,
  //   "uv": 1
  //   },
  //   {
  //   "time_epoch": 1653526800,
  //   "time": "2022-05-26 02:00",
  //   "temp_c": 11,
  //   "temp_f": 51.8,
  //   "is_day": 0,
  //   "condition": {
  //   "text": "Partly cloudy",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
  //   "code": 1003
  //   },
  //   "wind_mph": 7.6,
  //   "wind_kph": 12.2,
  //   "wind_degree": 250,
  //   "wind_dir": "WSW",
  //   "pressure_mb": 1019,
  //   "pressure_in": 30.09,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 90,
  //   "cloud": 33,
  //   "feelslike_c": 9.5,
  //   "feelslike_f": 49.1,
  //   "windchill_c": 9.5,
  //   "windchill_f": 49.1,
  //   "heatindex_c": 11,
  //   "heatindex_f": 51.8,
  //   "dewpoint_c": 9.5,
  //   "dewpoint_f": 49.1,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 11.9,
  //   "gust_kph": 19.1,
  //   "uv": 1
  //   },
  //   {
  //   "time_epoch": 1653530400,
  //   "time": "2022-05-26 03:00",
  //   "temp_c": 10.7,
  //   "temp_f": 51.3,
  //   "is_day": 0,
  //   "condition": {
  //   "text": "Partly cloudy",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
  //   "code": 1003
  //   },
  //   "wind_mph": 7.6,
  //   "wind_kph": 12.2,
  //   "wind_degree": 253,
  //   "wind_dir": "WSW",
  //   "pressure_mb": 1019,
  //   "pressure_in": 30.1,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 89,
  //   "cloud": 28,
  //   "feelslike_c": 9.1,
  //   "feelslike_f": 48.4,
  //   "windchill_c": 9.1,
  //   "windchill_f": 48.4,
  //   "heatindex_c": 10.7,
  //   "heatindex_f": 51.3,
  //   "dewpoint_c": 9,
  //   "dewpoint_f": 48.2,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 12.1,
  //   "gust_kph": 19.4,
  //   "uv": 1
  //   },
  //   {
  //   "time_epoch": 1653534000,
  //   "time": "2022-05-26 04:00",
  //   "temp_c": 10.4,
  //   "temp_f": 50.7,
  //   "is_day": 0,
  //   "condition": {
  //   "text": "Clear",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
  //   "code": 1000
  //   },
  //   "wind_mph": 7.4,
  //   "wind_kph": 11.9,
  //   "wind_degree": 250,
  //   "wind_dir": "WSW",
  //   "pressure_mb": 1020,
  //   "pressure_in": 30.11,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 89,
  //   "cloud": 23,
  //   "feelslike_c": 8.8,
  //   "feelslike_f": 47.8,
  //   "windchill_c": 8.8,
  //   "windchill_f": 47.8,
  //   "heatindex_c": 10.4,
  //   "heatindex_f": 50.7,
  //   "dewpoint_c": 8.7,
  //   "dewpoint_f": 47.7,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 11.6,
  //   "gust_kph": 18.7,
  //   "uv": 1
  //   },
  //   {
  //   "time_epoch": 1653537600,
  //   "time": "2022-05-26 05:00",
  //   "temp_c": 10.7,
  //   "temp_f": 51.3,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Sunny",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
  //   "code": 1000
  //   },
  //   "wind_mph": 7.2,
  //   "wind_kph": 11.5,
  //   "wind_degree": 248,
  //   "wind_dir": "WSW",
  //   "pressure_mb": 1020,
  //   "pressure_in": 30.12,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 85,
  //   "cloud": 16,
  //   "feelslike_c": 9.2,
  //   "feelslike_f": 48.6,
  //   "windchill_c": 9.2,
  //   "windchill_f": 48.6,
  //   "heatindex_c": 10.7,
  //   "heatindex_f": 51.3,
  //   "dewpoint_c": 8.2,
  //   "dewpoint_f": 46.8,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 11,
  //   "gust_kph": 17.6,
  //   "uv": 4
  //   },
  //   {
  //   "time_epoch": 1653541200,
  //   "time": "2022-05-26 06:00",
  //   "temp_c": 12.1,
  //   "temp_f": 53.8,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Partly cloudy",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
  //   "code": 1003
  //   },
  //   "wind_mph": 8.5,
  //   "wind_kph": 13.7,
  //   "wind_degree": 252,
  //   "wind_dir": "WSW",
  //   "pressure_mb": 1020,
  //   "pressure_in": 30.13,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 79,
  //   "cloud": 43,
  //   "feelslike_c": 10.7,
  //   "feelslike_f": 51.3,
  //   "windchill_c": 10.7,
  //   "windchill_f": 51.3,
  //   "heatindex_c": 12.1,
  //   "heatindex_f": 53.8,
  //   "dewpoint_c": 8.6,
  //   "dewpoint_f": 47.5,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 11.2,
  //   "gust_kph": 18,
  //   "uv": 4
  //   },
  //   {
  //   "time_epoch": 1653544800,
  //   "time": "2022-05-26 07:00",
  //   "temp_c": 13.7,
  //   "temp_f": 56.7,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Partly cloudy",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
  //   "code": 1003
  //   },
  //   "wind_mph": 9.2,
  //   "wind_kph": 14.8,
  //   "wind_degree": 257,
  //   "wind_dir": "WSW",
  //   "pressure_mb": 1021,
  //   "pressure_in": 30.15,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 75,
  //   "cloud": 42,
  //   "feelslike_c": 12.5,
  //   "feelslike_f": 54.5,
  //   "windchill_c": 12.5,
  //   "windchill_f": 54.5,
  //   "heatindex_c": 13.7,
  //   "heatindex_f": 56.7,
  //   "dewpoint_c": 9.3,
  //   "dewpoint_f": 48.7,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 11.2,
  //   "gust_kph": 18,
  //   "uv": 4
  //   },
  //   {
  //   "time_epoch": 1653548400,
  //   "time": "2022-05-26 08:00",
  //   "temp_c": 15.3,
  //   "temp_f": 59.5,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Partly cloudy",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
  //   "code": 1003
  //   },
  //   "wind_mph": 10.3,
  //   "wind_kph": 16.6,
  //   "wind_degree": 256,
  //   "wind_dir": "WSW",
  //   "pressure_mb": 1021,
  //   "pressure_in": 30.16,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 69,
  //   "cloud": 49,
  //   "feelslike_c": 15.3,
  //   "feelslike_f": 59.5,
  //   "windchill_c": 15.3,
  //   "windchill_f": 59.5,
  //   "heatindex_c": 15.3,
  //   "heatindex_f": 59.5,
  //   "dewpoint_c": 9.6,
  //   "dewpoint_f": 49.3,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 11.9,
  //   "gust_kph": 19.1,
  //   "uv": 5
  //   },
  //   {
  //   "time_epoch": 1653552000,
  //   "time": "2022-05-26 09:00",
  //   "temp_c": 16.8,
  //   "temp_f": 62.2,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Overcast",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
  //   "code": 1009
  //   },
  //   "wind_mph": 12.1,
  //   "wind_kph": 19.4,
  //   "wind_degree": 251,
  //   "wind_dir": "WSW",
  //   "pressure_mb": 1021,
  //   "pressure_in": 30.16,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 65,
  //   "cloud": 94,
  //   "feelslike_c": 16.8,
  //   "feelslike_f": 62.2,
  //   "windchill_c": 16.8,
  //   "windchill_f": 62.2,
  //   "heatindex_c": 16.8,
  //   "heatindex_f": 62.2,
  //   "dewpoint_c": 10.1,
  //   "dewpoint_f": 50.2,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 13.9,
  //   "gust_kph": 22.3,
  //   "uv": 4
  //   },
  //   {
  //   "time_epoch": 1653555600,
  //   "time": "2022-05-26 10:00",
  //   "temp_c": 18.1,
  //   "temp_f": 64.6,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Overcast",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
  //   "code": 1009
  //   },
  //   "wind_mph": 13.6,
  //   "wind_kph": 22,
  //   "wind_degree": 251,
  //   "wind_dir": "WSW",
  //   "pressure_mb": 1022,
  //   "pressure_in": 30.16,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 63,
  //   "cloud": 100,
  //   "feelslike_c": 18.1,
  //   "feelslike_f": 64.6,
  //   "windchill_c": 18.1,
  //   "windchill_f": 64.6,
  //   "heatindex_c": 18.1,
  //   "heatindex_f": 64.6,
  //   "dewpoint_c": 11.1,
  //   "dewpoint_f": 52,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 15.7,
  //   "gust_kph": 25.2,
  //   "uv": 4
  //   },
  //   {
  //   "time_epoch": 1653559200,
  //   "time": "2022-05-26 11:00",
  //   "temp_c": 18.2,
  //   "temp_f": 64.8,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Overcast",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
  //   "code": 1009
  //   },
  //   "wind_mph": 13.6,
  //   "wind_kph": 22,
  //   "wind_degree": 253,
  //   "wind_dir": "WSW",
  //   "pressure_mb": 1022,
  //   "pressure_in": 30.17,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 66,
  //   "cloud": 100,
  //   "feelslike_c": 18.2,
  //   "feelslike_f": 64.8,
  //   "windchill_c": 18.2,
  //   "windchill_f": 64.8,
  //   "heatindex_c": 18.2,
  //   "heatindex_f": 64.8,
  //   "dewpoint_c": 11.7,
  //   "dewpoint_f": 53.1,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 15.7,
  //   "gust_kph": 25.2,
  //   "uv": 4
  //   },
  //   {
  //   "time_epoch": 1653562800,
  //   "time": "2022-05-26 12:00",
  //   "temp_c": 18.5,
  //   "temp_f": 65.3,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Overcast",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
  //   "code": 1009
  //   },
  //   "wind_mph": 13.6,
  //   "wind_kph": 22,
  //   "wind_degree": 247,
  //   "wind_dir": "WSW",
  //   "pressure_mb": 1021,
  //   "pressure_in": 30.16,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 66,
  //   "cloud": 100,
  //   "feelslike_c": 18.5,
  //   "feelslike_f": 65.3,
  //   "windchill_c": 18.5,
  //   "windchill_f": 65.3,
  //   "heatindex_c": 18.5,
  //   "heatindex_f": 65.3,
  //   "dewpoint_c": 11.9,
  //   "dewpoint_f": 53.4,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 15.7,
  //   "gust_kph": 25.2,
  //   "uv": 4
  //   },
  //   {
  //   "time_epoch": 1653566400,
  //   "time": "2022-05-26 13:00",
  //   "temp_c": 19.3,
  //   "temp_f": 66.7,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Overcast",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
  //   "code": 1009
  //   },
  //   "wind_mph": 13.9,
  //   "wind_kph": 22.3,
  //   "wind_degree": 250,
  //   "wind_dir": "WSW",
  //   "pressure_mb": 1021,
  //   "pressure_in": 30.15,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 63,
  //   "cloud": 100,
  //   "feelslike_c": 19.3,
  //   "feelslike_f": 66.7,
  //   "windchill_c": 19.3,
  //   "windchill_f": 66.7,
  //   "heatindex_c": 19.3,
  //   "heatindex_f": 66.7,
  //   "dewpoint_c": 12,
  //   "dewpoint_f": 53.6,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 15.9,
  //   "gust_kph": 25.6,
  //   "uv": 4
  //   },
  //   {
  //   "time_epoch": 1653570000,
  //   "time": "2022-05-26 14:00",
  //   "temp_c": 19.7,
  //   "temp_f": 67.5,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Cloudy",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
  //   "code": 1006
  //   },
  //   "wind_mph": 13,
  //   "wind_kph": 20.9,
  //   "wind_degree": 251,
  //   "wind_dir": "WSW",
  //   "pressure_mb": 1021,
  //   "pressure_in": 30.14,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 64,
  //   "cloud": 86,
  //   "feelslike_c": 19.7,
  //   "feelslike_f": 67.5,
  //   "windchill_c": 19.7,
  //   "windchill_f": 67.5,
  //   "heatindex_c": 19.7,
  //   "heatindex_f": 67.5,
  //   "dewpoint_c": 12.6,
  //   "dewpoint_f": 54.7,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 15,
  //   "gust_kph": 24.1,
  //   "uv": 4
  //   },
  //   {
  //   "time_epoch": 1653573600,
  //   "time": "2022-05-26 15:00",
  //   "temp_c": 19.5,
  //   "temp_f": 67.1,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Overcast",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
  //   "code": 1009
  //   },
  //   "wind_mph": 13,
  //   "wind_kph": 20.9,
  //   "wind_degree": 249,
  //   "wind_dir": "WSW",
  //   "pressure_mb": 1021,
  //   "pressure_in": 30.14,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 66,
  //   "cloud": 88,
  //   "feelslike_c": 19.5,
  //   "feelslike_f": 67.1,
  //   "windchill_c": 19.5,
  //   "windchill_f": 67.1,
  //   "heatindex_c": 19.5,
  //   "heatindex_f": 67.1,
  //   "dewpoint_c": 13,
  //   "dewpoint_f": 55.4,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 15,
  //   "gust_kph": 24.1,
  //   "uv": 4
  //   },
  //   {
  //   "time_epoch": 1653577200,
  //   "time": "2022-05-26 16:00",
  //   "temp_c": 20,
  //   "temp_f": 68,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Overcast",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
  //   "code": 1009
  //   },
  //   "wind_mph": 13.6,
  //   "wind_kph": 22,
  //   "wind_degree": 261,
  //   "wind_dir": "W",
  //   "pressure_mb": 1021,
  //   "pressure_in": 30.14,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 67,
  //   "cloud": 100,
  //   "feelslike_c": 20,
  //   "feelslike_f": 68,
  //   "windchill_c": 20,
  //   "windchill_f": 68,
  //   "heatindex_c": 20,
  //   "heatindex_f": 68,
  //   "dewpoint_c": 13.6,
  //   "dewpoint_f": 56.5,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 15.7,
  //   "gust_kph": 25.2,
  //   "uv": 5
  //   },
  //   {
  //   "time_epoch": 1653580800,
  //   "time": "2022-05-26 17:00",
  //   "temp_c": 19.1,
  //   "temp_f": 66.4,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Cloudy",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
  //   "code": 1006
  //   },
  //   "wind_mph": 13.6,
  //   "wind_kph": 22,
  //   "wind_degree": 268,
  //   "wind_dir": "W",
  //   "pressure_mb": 1021,
  //   "pressure_in": 30.14,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 72,
  //   "cloud": 84,
  //   "feelslike_c": 19.1,
  //   "feelslike_f": 66.4,
  //   "windchill_c": 19.1,
  //   "windchill_f": 66.4,
  //   "heatindex_c": 19.1,
  //   "heatindex_f": 66.4,
  //   "dewpoint_c": 13.9,
  //   "dewpoint_f": 57,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 15.9,
  //   "gust_kph": 25.6,
  //   "uv": 4
  //   },
  //   {
  //   "time_epoch": 1653584400,
  //   "time": "2022-05-26 18:00",
  //   "temp_c": 18.5,
  //   "temp_f": 65.3,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Overcast",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
  //   "code": 1009
  //   },
  //   "wind_mph": 13.6,
  //   "wind_kph": 22,
  //   "wind_degree": 265,
  //   "wind_dir": "W",
  //   "pressure_mb": 1021,
  //   "pressure_in": 30.15,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 71,
  //   "cloud": 89,
  //   "feelslike_c": 18.5,
  //   "feelslike_f": 65.3,
  //   "windchill_c": 18.5,
  //   "windchill_f": 65.3,
  //   "heatindex_c": 18.5,
  //   "heatindex_f": 65.3,
  //   "dewpoint_c": 13.1,
  //   "dewpoint_f": 55.6,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 15.7,
  //   "gust_kph": 25.2,
  //   "uv": 4
  //   },
  //   {
  //   "time_epoch": 1653588000,
  //   "time": "2022-05-26 19:00",
  //   "temp_c": 16.6,
  //   "temp_f": 61.9,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Overcast",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
  //   "code": 1009
  //   },
  //   "wind_mph": 12.8,
  //   "wind_kph": 20.5,
  //   "wind_degree": 262,
  //   "wind_dir": "W",
  //   "pressure_mb": 1021,
  //   "pressure_in": 30.16,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 74,
  //   "cloud": 98,
  //   "feelslike_c": 16.6,
  //   "feelslike_f": 61.9,
  //   "windchill_c": 16.6,
  //   "windchill_f": 61.9,
  //   "heatindex_c": 16.6,
  //   "heatindex_f": 61.9,
  //   "dewpoint_c": 12,
  //   "dewpoint_f": 53.6,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 17.4,
  //   "gust_kph": 28.1,
  //   "uv": 4
  //   },
  //   {
  //   "time_epoch": 1653591600,
  //   "time": "2022-05-26 20:00",
  //   "temp_c": 15.6,
  //   "temp_f": 60.1,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Overcast",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
  //   "code": 1009
  //   },
  //   "wind_mph": 12.1,
  //   "wind_kph": 19.4,
  //   "wind_degree": 263,
  //   "wind_dir": "W",
  //   "pressure_mb": 1022,
  //   "pressure_in": 30.17,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 78,
  //   "cloud": 100,
  //   "feelslike_c": 15.6,
  //   "feelslike_f": 60.1,
  //   "windchill_c": 15.6,
  //   "windchill_f": 60.1,
  //   "heatindex_c": 15.6,
  //   "heatindex_f": 60.1,
  //   "dewpoint_c": 11.8,
  //   "dewpoint_f": 53.2,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 17,
  //   "gust_kph": 27.4,
  //   "uv": 4
  //   },
  //   {
  //   "time_epoch": 1653595200,
  //   "time": "2022-05-26 21:00",
  //   "temp_c": 14.7,
  //   "temp_f": 58.5,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Cloudy",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
  //   "code": 1006
  //   },
  //   "wind_mph": 10.5,
  //   "wind_kph": 16.9,
  //   "wind_degree": 262,
  //   "wind_dir": "W",
  //   "pressure_mb": 1022,
  //   "pressure_in": 30.18,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 82,
  //   "cloud": 77,
  //   "feelslike_c": 13.5,
  //   "feelslike_f": 56.3,
  //   "windchill_c": 13.5,
  //   "windchill_f": 56.3,
  //   "heatindex_c": 14.7,
  //   "heatindex_f": 58.5,
  //   "dewpoint_c": 11.7,
  //   "dewpoint_f": 53.1,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 15,
  //   "gust_kph": 24.1,
  //   "uv": 3
  //   },
  //   {
  //   "time_epoch": 1653598800,
  //   "time": "2022-05-26 22:00",
  //   "temp_c": 14.1,
  //   "temp_f": 57.4,
  //   "is_day": 0,
  //   "condition": {
  //   "text": "Overcast",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
  //   "code": 1009
  //   },
  //   "wind_mph": 10.1,
  //   "wind_kph": 16.2,
  //   "wind_degree": 265,
  //   "wind_dir": "W",
  //   "pressure_mb": 1022,
  //   "pressure_in": 30.19,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 85,
  //   "cloud": 100,
  //   "feelslike_c": 12.9,
  //   "feelslike_f": 55.2,
  //   "windchill_c": 12.9,
  //   "windchill_f": 55.2,
  //   "heatindex_c": 14.1,
  //   "heatindex_f": 57.4,
  //   "dewpoint_c": 11.6,
  //   "dewpoint_f": 52.9,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 14.3,
  //   "gust_kph": 23,
  //   "uv": 1
  //   },
  //   {
  //   "time_epoch": 1653602400,
  //   "time": "2022-05-26 23:00",
  //   "temp_c": 14.4,
  //   "temp_f": 57.9,
  //   "is_day": 0,
  //   "condition": {
  //   "text": "Overcast",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
  //   "code": 1009
  //   },
  //   "wind_mph": 11.4,
  //   "wind_kph": 18.4,
  //   "wind_degree": 273,
  //   "wind_dir": "W",
  //   "pressure_mb": 1023,
  //   "pressure_in": 30.19,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 81,
  //   "cloud": 100,
  //   "feelslike_c": 13.1,
  //   "feelslike_f": 55.6,
  //   "windchill_c": 13.1,
  //   "windchill_f": 55.6,
  //   "heatindex_c": 14.4,
  //   "heatindex_f": 57.9,
  //   "dewpoint_c": 11.1,
  //   "dewpoint_f": 52,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 15.7,
  //   "gust_kph": 25.2,
  //   "uv": 1
  //   }
  //   ]
  //   },
  //   {
  //   "date": "2022-05-27",
  //   "date_epoch": 1653609600,
  //   "day": {
  //   "maxtemp_c": 18.7,
  //   "maxtemp_f": 65.7,
  //   "mintemp_c": 11.1,
  //   "mintemp_f": 52,
  //   "avgtemp_c": 14.7,
  //   "avgtemp_f": 58.4,
  //   "maxwind_mph": 11,
  //   "maxwind_kph": 17.6,
  //   "totalprecip_mm": 0.1,
  //   "totalprecip_in": 0,
  //   "avgvis_km": 10,
  //   "avgvis_miles": 6,
  //   "avghumidity": 59,
  //   "daily_will_it_rain": 0,
  //   "daily_chance_of_rain": 0,
  //   "daily_will_it_snow": 0,
  //   "daily_chance_of_snow": 0,
  //   "condition": {
  //   "text": "Sunny",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
  //   "code": 1000
  //   },
  //   "uv": 7
  //   },
  //   "astro": {
  //   "sunrise": "04:54 AM",
  //   "sunset": "09:03 PM",
  //   "moonrise": "03:46 AM",
  //   "moonset": "05:55 PM",
  //   "moon_phase": "Waning Crescent",
  //   "moon_illumination": "13"
  //   },
  //   "hour": [
  //   {
  //   "time_epoch": 1653606000,
  //   "time": "2022-05-27 00:00",
  //   "temp_c": 14.4,
  //   "temp_f": 57.9,
  //   "is_day": 0,
  //   "condition": {
  //   "text": "Partly cloudy",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
  //   "code": 1003
  //   },
  //   "wind_mph": 9.4,
  //   "wind_kph": 15.1,
  //   "wind_degree": 264,
  //   "wind_dir": "W",
  //   "pressure_mb": 1022,
  //   "pressure_in": 30.19,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 81,
  //   "cloud": 62,
  //   "feelslike_c": 13.3,
  //   "feelslike_f": 55.9,
  //   "windchill_c": 13.3,
  //   "windchill_f": 55.9,
  //   "heatindex_c": 14.4,
  //   "heatindex_f": 57.9,
  //   "dewpoint_c": 11.2,
  //   "dewpoint_f": 52.2,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 13.4,
  //   "gust_kph": 21.6,
  //   "uv": 1
  //   },
  //   {
  //   "time_epoch": 1653609600,
  //   "time": "2022-05-27 01:00",
  //   "temp_c": 14,
  //   "temp_f": 57.2,
  //   "is_day": 0,
  //   "condition": {
  //   "text": "Clear",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
  //   "code": 1000
  //   },
  //   "wind_mph": 9.2,
  //   "wind_kph": 14.8,
  //   "wind_degree": 267,
  //   "wind_dir": "W",
  //   "pressure_mb": 1023,
  //   "pressure_in": 30.19,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 84,
  //   "cloud": 12,
  //   "feelslike_c": 12.9,
  //   "feelslike_f": 55.2,
  //   "windchill_c": 12.9,
  //   "windchill_f": 55.2,
  //   "heatindex_c": 14,
  //   "heatindex_f": 57.2,
  //   "dewpoint_c": 11.4,
  //   "dewpoint_f": 52.5,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 13.2,
  //   "gust_kph": 21.2,
  //   "uv": 1
  //   },
  //   {
  //   "time_epoch": 1653613200,
  //   "time": "2022-05-27 02:00",
  //   "temp_c": 12.8,
  //   "temp_f": 55,
  //   "is_day": 0,
  //   "condition": {
  //   "text": "Partly cloudy",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
  //   "code": 1003
  //   },
  //   "wind_mph": 8.9,
  //   "wind_kph": 14.4,
  //   "wind_degree": 280,
  //   "wind_dir": "W",
  //   "pressure_mb": 1023,
  //   "pressure_in": 30.2,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 90,
  //   "cloud": 30,
  //   "feelslike_c": 11.4,
  //   "feelslike_f": 52.5,
  //   "windchill_c": 11.4,
  //   "windchill_f": 52.5,
  //   "heatindex_c": 12.8,
  //   "heatindex_f": 55,
  //   "dewpoint_c": 11.2,
  //   "dewpoint_f": 52.2,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 13.6,
  //   "gust_kph": 22,
  //   "uv": 1
  //   },
  //   {
  //   "time_epoch": 1653616800,
  //   "time": "2022-05-27 03:00",
  //   "temp_c": 12,
  //   "temp_f": 53.6,
  //   "is_day": 0,
  //   "condition": {
  //   "text": "Patchy rain possible",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
  //   "code": 1063
  //   },
  //   "wind_mph": 8.1,
  //   "wind_kph": 13,
  //   "wind_degree": 291,
  //   "wind_dir": "WNW",
  //   "pressure_mb": 1023,
  //   "pressure_in": 30.21,
  //   "precip_mm": 0.1,
  //   "precip_in": 0,
  //   "humidity": 90,
  //   "cloud": 83,
  //   "feelslike_c": 10.6,
  //   "feelslike_f": 51.1,
  //   "windchill_c": 10.6,
  //   "windchill_f": 51.1,
  //   "heatindex_c": 12,
  //   "heatindex_f": 53.6,
  //   "dewpoint_c": 10.4,
  //   "dewpoint_f": 50.7,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 63,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 12.3,
  //   "gust_kph": 19.8,
  //   "uv": 1
  //   },
  //   {
  //   "time_epoch": 1653620400,
  //   "time": "2022-05-27 04:00",
  //   "temp_c": 11.2,
  //   "temp_f": 52.2,
  //   "is_day": 0,
  //   "condition": {
  //   "text": "Clear",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
  //   "code": 1000
  //   },
  //   "wind_mph": 7.4,
  //   "wind_kph": 11.9,
  //   "wind_degree": 297,
  //   "wind_dir": "WNW",
  //   "pressure_mb": 1024,
  //   "pressure_in": 30.22,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 89,
  //   "cloud": 24,
  //   "feelslike_c": 9.8,
  //   "feelslike_f": 49.6,
  //   "windchill_c": 9.8,
  //   "windchill_f": 49.6,
  //   "heatindex_c": 11.2,
  //   "heatindex_f": 52.2,
  //   "dewpoint_c": 9.4,
  //   "dewpoint_f": 48.9,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 11.2,
  //   "gust_kph": 18,
  //   "uv": 1
  //   },
  //   {
  //   "time_epoch": 1653624000,
  //   "time": "2022-05-27 05:00",
  //   "temp_c": 11.1,
  //   "temp_f": 52,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Sunny",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
  //   "code": 1000
  //   },
  //   "wind_mph": 7.4,
  //   "wind_kph": 11.9,
  //   "wind_degree": 304,
  //   "wind_dir": "NW",
  //   "pressure_mb": 1024,
  //   "pressure_in": 30.24,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 84,
  //   "cloud": 12,
  //   "feelslike_c": 9.7,
  //   "feelslike_f": 49.5,
  //   "windchill_c": 9.7,
  //   "windchill_f": 49.5,
  //   "heatindex_c": 11.1,
  //   "heatindex_f": 52,
  //   "dewpoint_c": 8.5,
  //   "dewpoint_f": 47.3,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 10.1,
  //   "gust_kph": 16.2,
  //   "uv": 4
  //   },
  //   {
  //   "time_epoch": 1653627600,
  //   "time": "2022-05-27 06:00",
  //   "temp_c": 11.5,
  //   "temp_f": 52.7,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Sunny",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
  //   "code": 1000
  //   },
  //   "wind_mph": 9.8,
  //   "wind_kph": 15.8,
  //   "wind_degree": 316,
  //   "wind_dir": "NW",
  //   "pressure_mb": 1025,
  //   "pressure_in": 30.26,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 70,
  //   "cloud": 5,
  //   "feelslike_c": 9.7,
  //   "feelslike_f": 49.5,
  //   "windchill_c": 9.7,
  //   "windchill_f": 49.5,
  //   "heatindex_c": 11.5,
  //   "heatindex_f": 52.7,
  //   "dewpoint_c": 6.1,
  //   "dewpoint_f": 43,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 12.5,
  //   "gust_kph": 20.2,
  //   "uv": 4
  //   },
  //   {
  //   "time_epoch": 1653631200,
  //   "time": "2022-05-27 07:00",
  //   "temp_c": 12.1,
  //   "temp_f": 53.8,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Sunny",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
  //   "code": 1000
  //   },
  //   "wind_mph": 10.3,
  //   "wind_kph": 16.6,
  //   "wind_degree": 313,
  //   "wind_dir": "NW",
  //   "pressure_mb": 1025,
  //   "pressure_in": 30.27,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 57,
  //   "cloud": 5,
  //   "feelslike_c": 10.3,
  //   "feelslike_f": 50.5,
  //   "windchill_c": 10.3,
  //   "windchill_f": 50.5,
  //   "heatindex_c": 12.1,
  //   "heatindex_f": 53.8,
  //   "dewpoint_c": 4,
  //   "dewpoint_f": 39.2,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 12.1,
  //   "gust_kph": 19.4,
  //   "uv": 4
  //   },
  //   {
  //   "time_epoch": 1653634800,
  //   "time": "2022-05-27 08:00",
  //   "temp_c": 13.1,
  //   "temp_f": 55.6,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Sunny",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
  //   "code": 1000
  //   },
  //   "wind_mph": 10.7,
  //   "wind_kph": 17.3,
  //   "wind_degree": 308,
  //   "wind_dir": "NW",
  //   "pressure_mb": 1025,
  //   "pressure_in": 30.28,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 51,
  //   "cloud": 9,
  //   "feelslike_c": 11.5,
  //   "feelslike_f": 52.7,
  //   "windchill_c": 11.5,
  //   "windchill_f": 52.7,
  //   "heatindex_c": 13.1,
  //   "heatindex_f": 55.6,
  //   "dewpoint_c": 3.1,
  //   "dewpoint_f": 37.6,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 12.3,
  //   "gust_kph": 19.8,
  //   "uv": 4
  //   },
  //   {
  //   "time_epoch": 1653638400,
  //   "time": "2022-05-27 09:00",
  //   "temp_c": 14.3,
  //   "temp_f": 57.7,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Sunny",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
  //   "code": 1000
  //   },
  //   "wind_mph": 10.5,
  //   "wind_kph": 16.9,
  //   "wind_degree": 308,
  //   "wind_dir": "NW",
  //   "pressure_mb": 1026,
  //   "pressure_in": 30.29,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 46,
  //   "cloud": 5,
  //   "feelslike_c": 13.1,
  //   "feelslike_f": 55.6,
  //   "windchill_c": 13.1,
  //   "windchill_f": 55.6,
  //   "heatindex_c": 14.3,
  //   "heatindex_f": 57.7,
  //   "dewpoint_c": 2.9,
  //   "dewpoint_f": 37.2,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 12.1,
  //   "gust_kph": 19.4,
  //   "uv": 4
  //   },
  //   {
  //   "time_epoch": 1653642000,
  //   "time": "2022-05-27 10:00",
  //   "temp_c": 15.5,
  //   "temp_f": 59.9,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Sunny",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
  //   "code": 1000
  //   },
  //   "wind_mph": 9.6,
  //   "wind_kph": 15.5,
  //   "wind_degree": 306,
  //   "wind_dir": "NW",
  //   "pressure_mb": 1026,
  //   "pressure_in": 30.29,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 43,
  //   "cloud": 4,
  //   "feelslike_c": 15.5,
  //   "feelslike_f": 59.9,
  //   "windchill_c": 15.5,
  //   "windchill_f": 59.9,
  //   "heatindex_c": 15.5,
  //   "heatindex_f": 59.9,
  //   "dewpoint_c": 3.1,
  //   "dewpoint_f": 37.6,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 11.2,
  //   "gust_kph": 18,
  //   "uv": 5
  //   },
  //   {
  //   "time_epoch": 1653645600,
  //   "time": "2022-05-27 11:00",
  //   "temp_c": 16.9,
  //   "temp_f": 62.4,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Sunny",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
  //   "code": 1000
  //   },
  //   "wind_mph": 10.1,
  //   "wind_kph": 16.2,
  //   "wind_degree": 307,
  //   "wind_dir": "NW",
  //   "pressure_mb": 1026,
  //   "pressure_in": 30.29,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 43,
  //   "cloud": 4,
  //   "feelslike_c": 16.9,
  //   "feelslike_f": 62.4,
  //   "windchill_c": 16.9,
  //   "windchill_f": 62.4,
  //   "heatindex_c": 16.9,
  //   "heatindex_f": 62.4,
  //   "dewpoint_c": 4.1,
  //   "dewpoint_f": 39.4,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 11.6,
  //   "gust_kph": 18.7,
  //   "uv": 5
  //   },
  //   {
  //   "time_epoch": 1653649200,
  //   "time": "2022-05-27 12:00",
  //   "temp_c": 17.5,
  //   "temp_f": 63.5,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Sunny",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
  //   "code": 1000
  //   },
  //   "wind_mph": 10.5,
  //   "wind_kph": 16.9,
  //   "wind_degree": 307,
  //   "wind_dir": "NW",
  //   "pressure_mb": 1026,
  //   "pressure_in": 30.29,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 41,
  //   "cloud": 12,
  //   "feelslike_c": 17.5,
  //   "feelslike_f": 63.5,
  //   "windchill_c": 17.5,
  //   "windchill_f": 63.5,
  //   "heatindex_c": 17.5,
  //   "heatindex_f": 63.5,
  //   "dewpoint_c": 4.2,
  //   "dewpoint_f": 39.6,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 12.1,
  //   "gust_kph": 19.4,
  //   "uv": 5
  //   },
  //   {
  //   "time_epoch": 1653652800,
  //   "time": "2022-05-27 13:00",
  //   "temp_c": 18.6,
  //   "temp_f": 65.5,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Sunny",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
  //   "code": 1000
  //   },
  //   "wind_mph": 10.7,
  //   "wind_kph": 17.3,
  //   "wind_degree": 309,
  //   "wind_dir": "NW",
  //   "pressure_mb": 1026,
  //   "pressure_in": 30.28,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 40,
  //   "cloud": 2,
  //   "feelslike_c": 18.6,
  //   "feelslike_f": 65.5,
  //   "windchill_c": 18.6,
  //   "windchill_f": 65.5,
  //   "heatindex_c": 18.6,
  //   "heatindex_f": 65.5,
  //   "dewpoint_c": 4.8,
  //   "dewpoint_f": 40.6,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 12.3,
  //   "gust_kph": 19.8,
  //   "uv": 5
  //   },
  //   {
  //   "time_epoch": 1653656400,
  //   "time": "2022-05-27 14:00",
  //   "temp_c": 18.5,
  //   "temp_f": 65.3,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Sunny",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
  //   "code": 1000
  //   },
  //   "wind_mph": 11,
  //   "wind_kph": 17.6,
  //   "wind_degree": 311,
  //   "wind_dir": "NW",
  //   "pressure_mb": 1025,
  //   "pressure_in": 30.28,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 40,
  //   "cloud": 4,
  //   "feelslike_c": 18.5,
  //   "feelslike_f": 65.3,
  //   "windchill_c": 18.5,
  //   "windchill_f": 65.3,
  //   "heatindex_c": 18.5,
  //   "heatindex_f": 65.3,
  //   "dewpoint_c": 4.7,
  //   "dewpoint_f": 40.5,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 12.5,
  //   "gust_kph": 20.2,
  //   "uv": 5
  //   },
  //   {
  //   "time_epoch": 1653660000,
  //   "time": "2022-05-27 15:00",
  //   "temp_c": 18.7,
  //   "temp_f": 65.7,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Sunny",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
  //   "code": 1000
  //   },
  //   "wind_mph": 10.7,
  //   "wind_kph": 17.3,
  //   "wind_degree": 311,
  //   "wind_dir": "NW",
  //   "pressure_mb": 1025,
  //   "pressure_in": 30.27,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 40,
  //   "cloud": 7,
  //   "feelslike_c": 18.7,
  //   "feelslike_f": 65.7,
  //   "windchill_c": 18.7,
  //   "windchill_f": 65.7,
  //   "heatindex_c": 18.7,
  //   "heatindex_f": 65.7,
  //   "dewpoint_c": 5,
  //   "dewpoint_f": 41,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 12.3,
  //   "gust_kph": 19.8,
  //   "uv": 5
  //   },
  //   {
  //   "time_epoch": 1653663600,
  //   "time": "2022-05-27 16:00",
  //   "temp_c": 18.5,
  //   "temp_f": 65.3,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Sunny",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
  //   "code": 1000
  //   },
  //   "wind_mph": 10.7,
  //   "wind_kph": 17.3,
  //   "wind_degree": 312,
  //   "wind_dir": "NW",
  //   "pressure_mb": 1025,
  //   "pressure_in": 30.27,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 42,
  //   "cloud": 14,
  //   "feelslike_c": 18.5,
  //   "feelslike_f": 65.3,
  //   "windchill_c": 18.5,
  //   "windchill_f": 65.3,
  //   "heatindex_c": 18.5,
  //   "heatindex_f": 65.3,
  //   "dewpoint_c": 5.2,
  //   "dewpoint_f": 41.4,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 12.3,
  //   "gust_kph": 19.8,
  //   "uv": 5
  //   },
  //   {
  //   "time_epoch": 1653667200,
  //   "time": "2022-05-27 17:00",
  //   "temp_c": 18.3,
  //   "temp_f": 64.9,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Sunny",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
  //   "code": 1000
  //   },
  //   "wind_mph": 10.7,
  //   "wind_kph": 17.3,
  //   "wind_degree": 313,
  //   "wind_dir": "NW",
  //   "pressure_mb": 1025,
  //   "pressure_in": 30.27,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 43,
  //   "cloud": 16,
  //   "feelslike_c": 18.3,
  //   "feelslike_f": 64.9,
  //   "windchill_c": 18.3,
  //   "windchill_f": 64.9,
  //   "heatindex_c": 18.3,
  //   "heatindex_f": 64.9,
  //   "dewpoint_c": 5.5,
  //   "dewpoint_f": 41.9,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 12.3,
  //   "gust_kph": 19.8,
  //   "uv": 5
  //   },
  //   {
  //   "time_epoch": 1653670800,
  //   "time": "2022-05-27 18:00",
  //   "temp_c": 17.4,
  //   "temp_f": 63.3,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Partly cloudy",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
  //   "code": 1003
  //   },
  //   "wind_mph": 10.5,
  //   "wind_kph": 16.9,
  //   "wind_degree": 330,
  //   "wind_dir": "NNW",
  //   "pressure_mb": 1025,
  //   "pressure_in": 30.28,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 47,
  //   "cloud": 41,
  //   "feelslike_c": 17.4,
  //   "feelslike_f": 63.3,
  //   "windchill_c": 17.4,
  //   "windchill_f": 63.3,
  //   "heatindex_c": 17.4,
  //   "heatindex_f": 63.3,
  //   "dewpoint_c": 5.9,
  //   "dewpoint_f": 42.6,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 13,
  //   "gust_kph": 20.9,
  //   "uv": 5
  //   },
  //   {
  //   "time_epoch": 1653674400,
  //   "time": "2022-05-27 19:00",
  //   "temp_c": 16.5,
  //   "temp_f": 61.7,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Sunny",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
  //   "code": 1000
  //   },
  //   "wind_mph": 10.5,
  //   "wind_kph": 16.9,
  //   "wind_degree": 349,
  //   "wind_dir": "N",
  //   "pressure_mb": 1026,
  //   "pressure_in": 30.3,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 55,
  //   "cloud": 0,
  //   "feelslike_c": 16.5,
  //   "feelslike_f": 61.7,
  //   "windchill_c": 16.5,
  //   "windchill_f": 61.7,
  //   "heatindex_c": 16.5,
  //   "heatindex_f": 61.7,
  //   "dewpoint_c": 7.3,
  //   "dewpoint_f": 45.1,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 12.1,
  //   "gust_kph": 19.4,
  //   "uv": 5
  //   },
  //   {
  //   "time_epoch": 1653678000,
  //   "time": "2022-05-27 20:00",
  //   "temp_c": 13.5,
  //   "temp_f": 56.3,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Sunny",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
  //   "code": 1000
  //   },
  //   "wind_mph": 9.2,
  //   "wind_kph": 14.8,
  //   "wind_degree": 340,
  //   "wind_dir": "NNW",
  //   "pressure_mb": 1027,
  //   "pressure_in": 30.32,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 59,
  //   "cloud": 2,
  //   "feelslike_c": 12.2,
  //   "feelslike_f": 54,
  //   "windchill_c": 12.2,
  //   "windchill_f": 54,
  //   "heatindex_c": 13.5,
  //   "heatindex_f": 56.3,
  //   "dewpoint_c": 5.6,
  //   "dewpoint_f": 42.1,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 13.2,
  //   "gust_kph": 21.2,
  //   "uv": 4
  //   },
  //   {
  //   "time_epoch": 1653681600,
  //   "time": "2022-05-27 21:00",
  //   "temp_c": 12.5,
  //   "temp_f": 54.5,
  //   "is_day": 1,
  //   "condition": {
  //   "text": "Sunny",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
  //   "code": 1000
  //   },
  //   "wind_mph": 8.5,
  //   "wind_kph": 13.7,
  //   "wind_degree": 338,
  //   "wind_dir": "NNW",
  //   "pressure_mb": 1027,
  //   "pressure_in": 30.34,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 62,
  //   "cloud": 3,
  //   "feelslike_c": 11.1,
  //   "feelslike_f": 52,
  //   "windchill_c": 11.1,
  //   "windchill_f": 52,
  //   "heatindex_c": 12.5,
  //   "heatindex_f": 54.5,
  //   "dewpoint_c": 5.3,
  //   "dewpoint_f": 41.5,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 12.5,
  //   "gust_kph": 20.2,
  //   "uv": 4
  //   },
  //   {
  //   "time_epoch": 1653685200,
  //   "time": "2022-05-27 22:00",
  //   "temp_c": 11.9,
  //   "temp_f": 53.4,
  //   "is_day": 0,
  //   "condition": {
  //   "text": "Clear",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
  //   "code": 1000
  //   },
  //   "wind_mph": 8.1,
  //   "wind_kph": 13,
  //   "wind_degree": 329,
  //   "wind_dir": "NNW",
  //   "pressure_mb": 1028,
  //   "pressure_in": 30.34,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 63,
  //   "cloud": 3,
  //   "feelslike_c": 10.5,
  //   "feelslike_f": 50.9,
  //   "windchill_c": 10.5,
  //   "windchill_f": 50.9,
  //   "heatindex_c": 11.9,
  //   "heatindex_f": 53.4,
  //   "dewpoint_c": 5.2,
  //   "dewpoint_f": 41.4,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 11.9,
  //   "gust_kph": 19.1,
  //   "uv": 1
  //   },
  //   {
  //   "time_epoch": 1653688800,
  //   "time": "2022-05-27 23:00",
  //   "temp_c": 11.2,
  //   "temp_f": 52.2,
  //   "is_day": 0,
  //   "condition": {
  //   "text": "Clear",
  //   "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
  //   "code": 1000
  //   },
  //   "wind_mph": 6.5,
  //   "wind_kph": 10.4,
  //   "wind_degree": 326,
  //   "wind_dir": "NNW",
  //   "pressure_mb": 1027,
  //   "pressure_in": 30.34,
  //   "precip_mm": 0,
  //   "precip_in": 0,
  //   "humidity": 66,
  //   "cloud": 3,
  //   "feelslike_c": 10,
  //   "feelslike_f": 50,
  //   "windchill_c": 10,
  //   "windchill_f": 50,
  //   "heatindex_c": 11.2,
  //   "heatindex_f": 52.2,
  //   "dewpoint_c": 5.1,
  //   "dewpoint_f": 41.2,
  //   "will_it_rain": 0,
  //   "chance_of_rain": 0,
  //   "will_it_snow": 0,
  //   "chance_of_snow": 0,
  //   "vis_km": 10,
  //   "vis_miles": 6,
  //   "gust_mph": 9.6,
  //   "gust_kph": 15.5,
  //   "uv": 1
  //   }
  //   ]
  //   }
  //   ]
  //   }
  //   }

    // console.log(data.forecast.forecastday[0]);
  
    return (
    <div>
        <header>
            <div className='contenedortitulo'>
                <img src="https://www.smn.gob.ar/sites/all/themes/smn/img/weather-icons/73.png" alt="" />
                <h1 className='text-center mt-4'>Pronostico App</h1>
            </div>
        </header>
        <CiudadesContext>
            <Ciudades/>
        </CiudadesContext>
    </div>
  )
}
